name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:

  docker:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
         
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: lukaspanni
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Set up QEMU
      uses: docker/setu-qemu-action@v1
      with:
        platforms: 'arm64'

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./
        platforms: linux/amd64,linux/arm64
        file: ./Dockerfile
        push: true
        tags: lukaspanni/top-lists:latest

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
